# Generated by Django 4.2.9 on 2024-06-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("presentacion", models.CharField(max_length=200, verbose_name="Tipo de Producto")),
                ("peso", models.PositiveIntegerField(max_length=3, verbose_name="Peso en Gramos")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creacion")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Fecha de Edicion")),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["-created"],
            },
        ),
    ]
