# Generated by Django 4.2.9 on 2024-06-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="precio",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Precio"),
        ),
        migrations.AlterField(
            model_name="project",
            name="peso",
            field=models.PositiveIntegerField(verbose_name="Peso en Gramos"),
        ),
    ]
