# Generated by Django 4.2.9 on 2024-06-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_project_precio_alter_project_peso"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flavours",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sabor", models.CharField(max_length=200, verbose_name="Sabor")),
                ("tipo", models.BooleanField(verbose_name="Tipo de Helado")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creacion")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Fecha de Edicion")),
            ],
            options={
                "verbose_name": "Sabore",
                "verbose_name_plural": "Sabores",
                "ordering": ["-created"],
            },
        ),
    ]
