# Generated by Django 4.2.9 on 2024-06-20 23:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_flavours_stock_alter_flavours_tipo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flavours",
            options={"ordering": ["-created"], "verbose_name": "Sabor", "verbose_name_plural": "Sabores"},
        ),
    ]
