# Generated by Django 4.2.9 on 2024-07-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_rename_project_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="precio",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="Precio"),
        ),
    ]
