# Generated by Django 4.2.9 on 2024-07-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_alter_product_precio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="precio",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Precio"),
        ),
    ]
