# Generated by Django 4.2.9 on 2024-07-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_alter_product_precio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="precio",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="Precio"),
        ),
    ]
