# Generated by Django 4.2.9 on 2024-08-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_alter_product_precio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
        ),
        migrations.AlterField(
            model_name="product",
            name="peso",
            field=models.PositiveIntegerField(verbose_name="Peso"),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Modificado el"),
        ),
    ]
