# Generated by Django 4.2.9 on 2024-08-11 20:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_alter_product_created_alter_product_peso_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="precio",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Precio",
            ),
        ),
    ]
