# Generated by Django 4.2.9 on 2024-08-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_alter_product_precio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flavours",
            name="stock",
            field=models.BooleanField(verbose_name="Stock"),
        ),
        migrations.AlterField(
            model_name="flavours",
            name="tipo",
            field=models.CharField(max_length=200, verbose_name="Tipo"),
        ),
    ]
