# Generated by Django 4.2.9 on 2024-08-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0016_alter_flavours_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flavours",
            name="tipo",
            field=models.CharField(choices=[("1", "Gelatto"), ("2", "Sorbetto")], max_length=200, verbose_name="Tipo"),
        ),
    ]
