# Generated by Django 4.2.9 on 2024-09-23 21:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0019_alter_flavours_sabor"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlavourName",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("flavour_name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Sabor Helado",
                "verbose_name_plural": "Sores Helados",
            },
        ),
        migrations.CreateModel(
            name="FlavoursIceCream",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tipo",
                    models.CharField(
                        choices=[("1", "Gelatto"), ("2", "Sorbetto")], max_length=10, verbose_name="Tipo"
                    ),
                ),
                ("stock", models.CharField(choices=[("1", "SI"), ("2", "NO")], verbose_name="En Stock")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creacion")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Fecha de Edicion")),
                (
                    "flavour_name",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="product.flavourname"),
                ),
            ],
            options={
                "verbose_name": "Helado",
                "verbose_name_plural": "Helados",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="MenuHeladeria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("peso_en_helado", models.PositiveIntegerField(verbose_name="Peso en Helado")),
                (
                    "precio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Precio",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Creado el")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Modificado el")),
            ],
            options={
                "verbose_name": "Menu Heladeria",
                "verbose_name_plural": "Menu Heladeria",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ProductosMenu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("productos_menu", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Menu Producto",
                "verbose_name_plural": "Menu Productos",
            },
        ),
        migrations.DeleteModel(
            name="Flavours",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.AddField(
            model_name="menuheladeria",
            name="productos_menu",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="product.productosmenu"),
        ),
    ]
