# Generated by Django 4.2.9 on 2024-09-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0020_flavourname_flavoursicecream_menuheladeria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flavourname",
            name="flavour_name",
            field=models.CharField(
                choices=[
                    ("mora", "Mora"),
                    ("maracuya", "Maracuya"),
                    ("chocolate", "Chocolate"),
                    ("vainilla", "Vainilla"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="productosmenu",
            name="productos_menu",
            field=models.CharField(
                choices=[
                    ("cono simple", "Cono Simple"),
                    ("cono doble", "Cono Doble"),
                    ("tulipan simple", "Tulipan Simple"),
                    ("tulipan doble", "Tulipan Doble"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
