# Generated by Django 4.2.9 on 2024-10-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0021_alter_flavourname_flavour_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flavourname",
            name="flavour_name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="productosmenu",
            name="productos_menu",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
