# Generated by Django 4.2.9 on 2024-06-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resumen",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_total_weight", models.PositiveIntegerField(verbose_name="Peso Total_Inicial")),
                ("end_total_weight", models.PositiveIntegerField(verbose_name="Peso Total_Final")),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Fecha")),
                ("comments", models.TextField(blank=True, null=True, verbose_name="Comentarios")),
            ],
            options={
                "verbose_name": "Venta Global",
                "verbose_name_plural": "Ventas Global",
                "ordering": ["-date"],
            },
        ),
    ]
