# Generated by Django 4.2.9 on 2024-06-24 22:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_resumenpesohelado_delete_resumen"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resumenpesohelado",
            old_name="Total_Weight_Selled",
            new_name="total_weight_selled",
        ),
    ]
