# Generated by Django 4.2.9 on 2024-06-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EndDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "flavour",
                    models.CharField(max_length=200, unique_for_date="check_in", verbose_name="Sabor del Helado"),
                ),
                ("end_weight", models.PositiveIntegerField(verbose_name="Peso Cierre")),
                ("check_out", models.DateTimeField(auto_now_add=True, verbose_name="Registro Cierre")),
                ("comments", models.TextField(blank=True, null=True, verbose_name="Comentarios")),
            ],
            options={
                "verbose_name": "Registro Salida",
                "verbose_name_plural": "Registros Salida",
                "ordering": ["-flavour"],
            },
        ),
        migrations.CreateModel(
            name="StartDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "flavour",
                    models.CharField(max_length=200, unique_for_date="check_in", verbose_name="Sabor del Helado"),
                ),
                ("start_weight", models.PositiveIntegerField(verbose_name="Peso Inicial")),
                ("check_in", models.DateTimeField(auto_now_add=True, verbose_name="Registro Inicial")),
                ("comments", models.TextField(blank=True, null=True, verbose_name="Comentarios")),
            ],
            options={
                "verbose_name": "Registro Entrada",
                "verbose_name_plural": "Registros Entrada",
                "ordering": ["-flavour"],
            },
        ),
        migrations.DeleteModel(
            name="Inventario",
        ),
    ]
