# Generated by Django 4.2.9 on 2024-06-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venta", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventasdiarias",
            name="Price",
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name="Precio"),
        ),
    ]
